apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bakcend-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # remove if you have TLS
spec:
  ingressClassName: "nginx"
  rules:
    - host: old-monolith.tehend.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: old-monolith
                port:
                  number: 80